version: "3"
services:
  php:
    image: php:7.2.16-fpm
    # 仅对容器组暴露9000端口
    expose:
        - "9000"
    volumes:
      #代码路径映射
      - /data/path/to/code:/var/www/html
      # php日志目录映射
      - /data/docker-lnmp/log/php:/var/log/php-fpm
      # 配置文件映射
      - ./default-conf/www.conf:/etc/php-fpm.d/www.conf

  mysql:
    image: mysql:5.6.43
    environment:
      # 没有root密码
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

    ports:
      - "3306:3306"
    volumes:
      # 把本地的数据库的data目录映射到mysql镜像的路径里
      - /data/docker-lnmp/mysql:/var/lib/mysql

  nginx:
    image: nginx:1.14.2
    ports:
      - "80:80"
    volumes:
      # 配置文件映射
      - ./default-conf/nginx.conf:/etc/nginx/nginx.conf
      # 代码目录
      - /data/path/to/code:/var/www/html
      # nginx日志目录映射
      - /data/docker-lnmp/log/nginx:/var/log/nginx
    
